fixed workflow to push to pypi

diff --git a/.github/workflows/poll_and_publish.yml b/.github/workflows/poll_and_publish.yml
--- a/.github/workflows/poll_and_publish.yml
+++ b/.github/workflows/poll_and_publish.yml
@@ -23,11 +23,17 @@ jobs:
       - name: Fix and publish, iff there exists a tag in rocm/amdsmi that is not here.
         run: |
             chmod +x ./scripts/checkout_and_push_tag.sh
-            ./scripts/checkout_and_push_tag.sh
+            ./scripts/checkout_and_push_tag.sh || true  # Avoid failing the workflow on exit code 1
+
+            if [ $? -eq 0 ]; then
+              echo "::set-output name=tag_published::true"
+            else
+              echo "::set-output name=tag_published::false"
+            fi
 
   publish:
     runs-on: ubuntu-latest
-    if: startsWith(github.ref, 'refs/tags/')  # Run only if this is a tag push
+    if: ${{ needs.polling_amdsmi.outputs.tag_published == 'true' }}  # Run only if a new tag was published
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
